### ISSUE TITLE
which assets csv should I be using?

### ISSUE THREAD

**Issue by jhamman** [pangeo-data/pangeo-cmip6-cloud#16]
I'm finding that two different set of cloud assets are being used that has me confused. The two csvs are:

- https://storage.googleapis.com/cmip6/pangeo-cmip6.csv
  - referenced in many tutorials and intake-esm jsons
- https://storage.googleapis.com/cmip6/cmip6-zarr-consolidated-stores.csv
  - referenced in @naomi-henderson's emails after new stores are created and tutorials like this one: https://github.com/pangeo-gallery/cmip6/blob/master/basic_search_and_load.ipynb

I did check to make sure they weren't identical: 
```
wc -l ~/Downloads/pangeo-cmip6.csv ~/Downloads/cmip6-zarr-consolidated-stores.csv
  292308 /Users/jhamman/Downloads/pangeo-cmip6.csv
  292705 /Users/jhamman/Downloads/cmip6-zarr-consolidated-stores.csv
```
So my question is, which one should I be using and why are there two? Thanks!

**Comment by naomi-henderson** [comment]
@jhamman , the primary version is `cmip6-zarr-consolidated-stores.cvs`. The `pangeo-cmip6.csv` is an old name (pre-hackathon?). I update them both in adjacent lines in my python code, so it must be that the pangeo-cmip6.csv was still in cache.  I did update the catalog about an hour ago.  

So use either one - but because of the caching perhaps you want to switch back and forth (just kidding).

Not to make more problems, but I will repeat here that this catalog does not include any datasets which have serious issues listed in the official CMIP6 errata pages.  If you want to see ALL of the CMIP6 datasets in this bucket, including those with reported problems, there is an additional catalog, `cmip6-zarr-consolidated-stores-noQC.cvs`.  The `noQC` stands for 'no quality control'.

**Comment by naomi-henderson** [comment]
```
gsutil -m ls -l gs://cmip6/*.csv

  48441329  2020-09-28T20:26:09Z  gs://cmip6/cmip6-zarr-consolidated-stores-noQC.csv
  43008257  2020-09-28T20:26:31Z  gs://cmip6/cmip6-zarr-consolidated-stores.csv
    201673  2019-11-26T03:33:11Z  gs://cmip6/pangeo-cmip3.csv
    445997  2019-11-26T17:12:19Z  gs://cmip6/pangeo-cmip5.csv
  43008257  2020-09-28T20:26:34Z  gs://cmip6/pangeo-cmip6.csv
 
```

**Comment by rabernat** [comment]
> @jhamman , the primary version is `cmip6-zarr-consolidated-stores.cvs`. The `pangeo-cmip6.csv` is an old name (pre-hackathon?). I update them both in adjacent lines in my python code, so it must be that the pangeo-cmip6.csv was still in cache. I did update the catalog about an hour ago.
> 
> So use either one - but because of the caching perhaps you want to switch back and forth (just kidding).
> 
> Not to make more problems, but I will repeat here that this catalog does not include any datasets which have serious issues listed in the official CMIP6 errata pages. If you want to see ALL of the CMIP6 datasets in this bucket, including those with reported problems, there is an additional catalog, `cmip6-zarr-consolidated-stores-noQC.cvs`. The `noQC` stands for 'no quality control'.

This seems like really crucial information. Can we have a page on the [CMIP6 cloud docs](https://pangeo-data.github.io/pangeo-cmip6-cloud/index.html) which basically quotes it verbatim?

If certain CSV files are no longer maintained (e.g. `pangeo-cmip6.csv`), we should remove them, or replace them with a text-based message redirecting to the current file. I should note that in [these docs](https://pangeo-data.github.io/pangeo-cmip6-cloud/overview.html), @charlesbluca has linked to: https://storage.googleapis.com/cmip6/pangeo-cmip6.csv

**Comment by jhamman** [comment]
Thanks @naomi-henderson for the clarification! I must have caught the csvs mid-update. I'll leave this open to allow @rabernat's final points be addressed.

**Comment by naomi-henderson** [comment]
The only duplicate CSV file is `pangeo-cmip6.csv`.  

Let me play devil's advocate and say that, at least for now, it is less of a burden to keep the two names than to disrupt the workflow of multiple researchers who would have their `intake-esm` json files messed up or break existing shared notebooks.  If we consciously try to squash the `pangeo-cmip6.csv` name for the next year, we could wait until then to retire the duplicate file. The pangeo-forge effort and the big query effort might make all of these obsolete by then, anyway.  
 
Thoughts?

**Comment by rabernat** [comment]
> it is less of a burden to keep the two names than to disrupt the workflow of multiple researchers who would have their `intake-esm` json files messed up or break existing shared notebooks.

Very good point Naomi! I appreciate your thought to the user experience.

> The pangeo-forge effort and the big query effort might make all of these obsolete by then, anyway.

Big query could happen soon. That really depends on you and Charles. Pangeo forge is quite a bit farther off.

**Comment by charlesbluca** [comment]
Thanks for addressing this; I currently have a PR open where I linked to the correct "non-QC" files, but based on this discussion I'm now expanding on the differences contained in the `-noQC` files as well.

@naomi-henderson, I have a couple of questions relevant to this:

- Could you give some insight on what `new` and `onhold` status means for issues in the Errata pages? I'd imagine `new` just means the issue has been posted without a resolution yet, but am unsure of if there is a relationship to `onhold` and the documentation doens't mention either status.
- Is there any verbose description of what the `version` column represents (other than simply the version of the dataset listed on ESGF)? That's one of the few columns we left with a vague description in our [BigQuery schema](https://github.com/pangeo-forge/cmip6-pipeline/blob/master/schema/%20cmip6_zarr_consolidated_stores_noQC.json).

**Comment by naomi-henderson** [comment]
I think `new` and `onhold` mean whatever the modelers want them to mean ... To really understand this document, each issue would need to be researched carefully to see what is really meant.

The `version` column description should be something like `approximate date of model output file` (from the listings of the Data Reference Syntax (DRS) components [here](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit#)

**Comment by jbusecke** [comment]
From now on I recommend using the assets for the new [2.0 zarr catalog](https://github.com/leap-stc/cmip6-leap-feedstock#how-to-access-the-newly-uploaded-data). Ill close this, please feel free to reopen an issue over there is things are still unclear.
