### ISSUE TITLE
Size of pangeo cloud holding

### ISSUE THREAD

**Issue by jbusecke** [pangeo-data/pangeo-cmip6-cloud#37]
@aradhakrishnanGFDL had questions about the size of the cloud holdings. Do we have a method of checking on this currently?

cc @naomi-henderson @rabernat

**Comment by aradhakrishnanGFDL** [comment]
@jbusecke From the AWS management console, S3 and then S3 storage lens provides quick highlights including the size. Include only the current versions as a filter. Hope that helps!

**Comment by jbusecke** [comment]
it does. Thanks a lot. Ill try to work on this next week, since I have to get the credentials first. Does anybody know if comparable tools exist for GCS?

**Comment by delgadom** [comment]
Not sure if this is what you're looking for, but you can view the size of a bucket & object count on the monitoring dashboard:

https://console.cloud.google.com/monitoring/dashboards/resourceList/gcs_bucket?project=PROJECT_ID

**Comment by jbusecke** [comment]
Moved to https://github.com/leap-stc/cmip6-leap-feedstock/issues/93

**Comment by delgadom** [comment]
You definitely do need pretty broad permissions. Just checking - did you replace or drop the project id parameter? But yeah you’ll need a pretty wide set of permissions on the project. I’m not sure how grant projects work - you could check with your rep to see if this is possible. Hope that’s helpful!

**Comment by durack1** [comment]
> You definitely do need pretty broad permissions. Just checking - did you replace or drop the project id parameter? But yeah you’ll need a pretty wide set of permissions on the project. I’m not sure how grant projects work - you could check with your rep to see if this is possible. Hope that’s helpful!

I literally used the exact url listed above https://github.com/pangeo-data/pangeo-cmip6-cloud/issues/37#issuecomment-1917621152 - so maybe I need to switchout "csiro" or whatever the correct ID is?
